default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  host: localhost
  pool: 5

development:
  <<: *default
  database: achieve_development

test:
  <<: *default
  database: achieve_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
